conf/turnkey.d/postfix-local: port 25 check (causes a silent error that was a PITA to debug)

diff --git a/conf/turnkey.d/postfix-local b/conf/turnkey.d/postfix-local
--- a/conf/turnkey.d/postfix-local
+++ b/conf/turnkey.d/postfix-local
@@ -1,8 +1,13 @@
 #!/bin/bash -e
 
+fatal() { "'$(basename "$0")' Error: $*" >&2; exit 1; }
+
 if [[ ! "$HOSTNAME" ]]; then
-    echo "'$(basename "$0")' error: hostname not defined"
-    return 1
+    fatal "Hostname not defined"
+fi
+
+if ! grep -q ':25' <(ss -tlnp); then
+    fatal "Port 25 is already in use - must be available to set up postfix"
 fi
 
 postconf -e inet_interfaces=localhost
