bookworm-18.0-wip

diff --git a/conf/bootstrap_apt b/conf/bootstrap_apt
--- a/conf/bootstrap_apt
+++ b/conf/bootstrap_apt
@@ -6,6 +6,7 @@
 #   - optional: TKL_TESTING
 #   - optional: BACKPORTS
 #   - optional: PHP_VERSION
+#   - optional: APT_PROXY_OVERRIDE
 
 # Note, to install packages from backports:
 # - set 'BACKPORTS=y'; and either:
@@ -18,6 +19,9 @@ fatal() {
 }
 
 [ -n "$CODENAME" ] || fatal "CODENAME is not set"
+if grep "NO_TURNKEY_APT_REPO" /turnkey-transition-info; then
+    TRANSITION_NO_TURNKEY_APT_REPO=y
+fi
 
 SOURCES_LIST=/etc/apt/sources.list.d
 PREFS_LIST=/etc/apt/preferences.d
@@ -25,19 +29,27 @@ CONF_DIR=/etc/apt/apt.conf.d
 mkdir -p $SOURCES_LIST $PREFS_LIST $CONF_DIR
 
 # TEMP support 17.0rc build on 16.x
-guest_build=$(cat /etc/debian_version | cut -d. -f1)
+guest_build=$(cat /etc/debian_version | cut -d. -f1 | cut -d/ -f2)
 BUSTER_BASE=""
 PROXY_PORT=3128
-if [[ $guest_build -eq 11 ]] && [[ -f /bullseye_on_buster ]]; then
+if [[ "$guest_build" -eq "11" ]] && [[ -f /bullseye_on_buster ]]; then
     export BUSTER_BASE=y
     PROXY_PORT=8124
 fi
 
-# Configure apt proxy
-cat > $CONF_DIR/01proxy <<EOF
+if [[ "${APT_PROXY_OVERRIDE,,}" -eq "disable" ]]; then
+    PROXY_PORT=
+elif [[ -n $APT_PROXY_OVERRIDE ]]; then
+    PROXY_PORT=$APT_PROXY_OVERRIDE
+fi
+
+if [[ -n $PROXY_PORT ]]; then
+    # Configure apt proxy
+    cat > $CONF_DIR/01proxy <<EOF
 Acquire::http::proxy "http://127.0.0.1:$PROXY_PORT";
 Acquire::https::proxy "http://127.0.0.1:$PROXY_PORT";
 EOF
+fi
 
 # update CA certs (custom cacher cert should already have been added)
 if [[ -e /usr/local/share/ca-certificates/squid_proxyCA.crt ]]; then
@@ -52,20 +64,22 @@ fi
 #   apt-cache policy php | sed -n "\|Candidate:|s|.*:\([0-9]\.[0-9]*\)+.*|\1|p"
 DEBIAN_PHP_V=7.4
 
-# keys are provided as ascii armoured for transparency; but secure apt requires
-# gpg keyring files
-key_dir=/usr/share/keyrings
-repos=(main security testing)
-for repo in ${repos[@]}; do
-    full_path=$key_dir/tkl-$CODENAME-$repo
-    keyring=$full_path.gpg
-    keyfile=$full_path.asc
-    gpg --no-default-keyring --keyring $keyring --import $keyfile
-    rm $keyfile
-done
-# ensure that gpg-agent is killed after processing keys
-kill -9 $(pidof gpg-agent) || true
-rm -rf $HOME/.gnupg
+if [[ -z "$TRANSITION_NO_TURNKEY_APT_REPO" ]]; then
+    # keys are provided as ascii armoured for transparency; but secure apt requires
+    # gpg keyring files
+    key_dir=/usr/share/keyrings
+    repos=(main security testing)
+    for repo in ${repos[@]}; do
+        full_path=$key_dir/tkl-$CODENAME-$repo
+        keyring=$full_path.gpg
+        keyfile=$full_path.asc
+        gpg --no-default-keyring --keyring $keyring --import $keyfile
+        rm $keyfile
+    done
+    # ensure that gpg-agent is killed after processing keys
+    kill -9 $(pidof gpg-agent) || true
+    rm -rf $HOME/.gnupg
+fi
 
 if [[ "$CODENAME" == "stretch" ]] || [[ "$CODENAME" == "buster" ]];then
     sec_repo="$CODENAME/updates"
@@ -84,9 +98,9 @@ EOF
 cat > $SOURCES_LIST/security.sources.list <<EOF
 deb [signed-by=$key_dir/tkl-$CODENAME-security.gpg] http://archive.turnkeylinux.org/debian $CODENAME-security main
 
-deb http://security.debian.org/ $sec_repo main
-deb http://security.debian.org/ $sec_repo contrib
-#deb http://security.debian.org/ $sec_repo non-free
+deb http://security.debian.org $sec_repo main
+deb http://security.debian.org $sec_repo contrib
+#deb http://security.debian.org $sec_repo non-free
 EOF
 
 TKL_TESTING_LIST=$SOURCES_LIST/turnkey-testing.list
@@ -99,6 +113,10 @@ cat > $DEB_BACKPORT_LIST.disabled <<EOF
 deb http://deb.debian.org/debian $CODENAME-backports main
 #deb http://deb.debian.org/debian $CODENAME-backports non-free
 EOF
+
+if [[ -n $TRANSITION_NO_TURNKEY_APT_REPO ]]; then
+    find $SOURCES_LIST -type f -exec sed -i '/archive.turnkeylinux.org/ s/^/#/g' {} \;
+fi
 
 if [ -n "$PHP_VERSION" ]; then
     # Use 3rd party sury.org repo
@@ -232,3 +250,5 @@ fi
 # This hack ensures that any changes to 'Suite' and 'Version' changes are
 # accepted and don't interupt install
 apt-get update --allow-releaseinfo-change
+# no idea why but build fails saying this dir doesn't exist if I don't do this
+mkdir -p /var/cache/apt/archives
