bugfix: JVM was not identified on amd64 builds (closes turnkeylinux/tracker#140)
- added JVM identification for amd64 builds
- added error handling to break the build if JVM cannot is not identified
- configure JAVA_HOME in /etc/default/tomcat (thanks @tssgery!)
  https://github.com/turnkeylinux/tracker/issues/140#issuecomment-30928963

diff --git a/conf/tomcat b/conf/tomcat
--- a/conf/tomcat
+++ b/conf/tomcat
@@ -1,19 +1,25 @@
 #!/bin/sh -ex
 
-# configure tomcat environment
+fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
+
+# identify JVM to use
+[ -e /usr/lib/jvm/java-1.5.0-sun ] && JVM=java-1.5.0-sun
+[ -e /usr/lib/jvm/java-6-sun ] && JVM=java-6-sun
+[ -e /usr/lib/jvm/java-6-openjdk ] && JVM=java-6-openjdk
+[ -e /usr/lib/jvm/java-6-openjdk-amd64 ] && JVM=java-6-openjdk-amd64
+
+[ -z "$JVM" ] && fatal "JVM to use could not be identified"
+
+# configure java/tomcat environment
 cat >> /etc/environment<<EOF
 CATALINA_HOME="/usr/share/tomcat6"
 CATALINA_BASE="/var/lib/tomcat6"
 CATALINA_OPTS="-server -Xms384M -Xmx512M -XX:MaxPermSize=256M"
+JAVA_HOME="/usr/lib/jvm/${JVM}"
 EOF
 
-# configure Java
-[ -d /usr/lib/jvm/java-1.5.0-sun ] && JVM=java-1.5.0-sun
-[ -d /usr/lib/jvm/java-6-sun ] && JVM=java-6-sun
-[ -d /usr/lib/jvm/java-6-openjdk ] && JVM=java-6-openjdk
-
 update-java-alternatives -s $JVM || true
-echo JAVA_HOME=\"/usr/lib/jvm/${JVM}\" >> /etc/environment
+echo JAVA_HOME=\"/usr/lib/jvm/${JVM}\" >> /etc/default/tomcat6
 
 # configure Apache if needed (Jk connector to Tomcat)
 if [ -e /etc/apache2/sites-available/jktomcat ]; then
